Feat/dash movement
OutcastsGameStudio/SR pull request #69
Opened 2024-12-02 14:28 UTC by LeonLighter

2024-12-03 12:41 UTC, Yanisslsl requested changes
Modifications a appliquer

2024-12-03 12:43 UTC, Hask0ll commented on Source/SR/Character/Components/Dash/SR_DashComponent.cpp
> +	//set the movement mode to falling
Il faut revoir la logique du Dash, partir plutot sur un Apply root motion add force ou une Physic custom

2024-12-03 12:43 UTC, Hask0ll commented on Source/SR/Character/Components/Dash/SR_DashComponent.cpp
> +	CharacterMovement->BrakingDecelerationFalling = 0.f;
Là SI le joueur a une collision avec un objet movable on glitch de la map

2024-12-03 12:43 UTC, Hask0ll commented on Source/SR/Character/Components/Dash/SR_DashComponent.h
> +	UCharacterMovementComponent* CharacterMovement = nullptr;
A voir si on fait la ref dans Begin play

2024-12-03 12:43 UTC, Hask0ll commented on Source/SR/Character/SR_Character.cpp
> +	if (bIsDashing)
Refacto ça

2024-12-03 12:43 UTC, Hask0ll commented on Source/SR/Character/SR_Character.cpp
> +{
Bouger la logique dans Dash

2024-12-04 14:09 UTC, Hask0ll approved these changes

2024-12-04 14:10 UTC, merged